name: la-covid
channels:
  - esri
  - conda-forge
dependencies:
  - arcgis==1.8.0
  - bokeh
  - cloudpickle
  - cookiecutter
  - dask
  - distributed
  - fsspec
  - h3-py
  - jupyterlab
  - murmurhash
  - mkdocs
  - nodejs
  - partd
  - pillow
  - pip
  - psutil
  - pylint
  - pytest
  - python-dotenv
  - python-graphviz
  - scipy
  - scikit-learn
  - seaborn
  - shapely
  - sodapy
  - swifter
  - sqlalchemy
  - tqdm
  - pip:
    - azure-storage-blob
    - dask_labextension
    - ipykernel
    - pyarrow
    - sodapy
    - sphinx
  